// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "schema.prisma",
  migrations: {
    path: "./migrations",
    seed: "ts-node --require tsconfig-paths/register -r dotenv/config seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
