import { MessageDto } from "@/message/message";

/** All possible socket events in a room. Used to listen for socket events */
enum RoomEvents {
  JOIN = "joinRoom",
  LEAVE = "leaveRoom",
  MESSAGE_POST_SUCCESS = "messagePostSuccess",
  MESSAGE_POST_FAILURE = "messagePostFailure",
  NEW_MESSAGE = "newMessage",
  POST_MESSAGE = "postMessage",
}

/** Client → Server: join a room's broadcast channel. */
interface JoinRoomPayload {
  roomId: string;
}

/** Client → Server: leave a room's broadcast channel. */
interface LeaveRoomPayload {
  roomId: string;
}

/** Client → Server: post a new message to a room. */
interface MessagePayload {
  temporaryMessageId: string; // Placeholder message id generated by client to track message send failures.
  content: string;
  roomId: string;
  sentAt: string; // ISO 8601 date string
}

export { RoomEvents, JoinRoomPayload, LeaveRoomPayload, MessagePayload };
